Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.datasets import fetch_openml

mnist = fetch_openml("miceprotein")
df = mnist.data.dropna()
df.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOpenMLError[0m                               Traceback (most recent call last)
Cell [0;32mIn[13], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatasets[39;00m [38;5;28;01mimport[39;00m fetch_openml
[0;32m----> 3[0m mnist [38;5;241m=[39m [43mfetch_openml[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mmiceprotein[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      4[0m df [38;5;241m=[39m mnist[38;5;241m.[39mdata[38;5;241m.[39mdropna()
[1;32m      5[0m df[38;5;241m.[39mhead()

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/sklearn/datasets/_openml.py:882[0m, in [0;36mfetch_openml[0;34m(name, version, data_id, data_home, target_column, cache, return_X_y, as_frame, n_retries, delay, parser)[0m
[1;32m    876[0m     [38;5;28;01mif[39;00m data_id [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    877[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    878[0m             [38;5;124m"[39m[38;5;124mDataset data_id=[39m[38;5;132;01m{}[39;00m[38;5;124m and name=[39m[38;5;132;01m{}[39;00m[38;5;124m passed, but you can only [39m[38;5;124m"[39m
[1;32m    879[0m             [38;5;124m"[39m[38;5;124mspecify a numeric data_id or a name, not [39m[38;5;124m"[39m
[1;32m    880[0m             [38;5;124m"[39m[38;5;124mboth.[39m[38;5;124m"[39m[38;5;241m.[39mformat(data_id, name)
[1;32m    881[0m         )
[0;32m--> 882[0m     data_info [38;5;241m=[39m [43m_get_data_info_by_name[49m[43m([49m
[1;32m    883[0m [43m        [49m[43mname[49m[43m,[49m[43m [49m[43mversion[49m[43m,[49m[43m [49m[43mdata_home[49m[43m,[49m[43m [49m[43mn_retries[49m[38;5;241;43m=[39;49m[43mn_retries[49m[43m,[49m[43m [49m[43mdelay[49m[38;5;241;43m=[39;49m[43mdelay[49m
[1;32m    884[0m [43m    [49m[43m)[49m
[1;32m    885[0m     data_id [38;5;241m=[39m data_info[[38;5;124m"[39m[38;5;124mdid[39m[38;5;124m"[39m]
[1;32m    886[0m [38;5;28;01melif[39;00m data_id [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    887[0m     [38;5;66;03m# from the previous if statement, it is given that name is None[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/sklearn/datasets/_openml.py:283[0m, in [0;36m_get_data_info_by_name[0;34m(name, version, data_home, n_retries, delay)[0m
[1;32m    281[0m url [38;5;241m=[39m _SEARCH_NAME[38;5;241m.[39mformat(name) [38;5;241m+[39m [38;5;124m"[39m[38;5;124m/status/active/[39m[38;5;124m"[39m
[1;32m    282[0m error_msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mNo active dataset [39m[38;5;132;01m{}[39;00m[38;5;124m found.[39m[38;5;124m"[39m[38;5;241m.[39mformat(name)
[0;32m--> 283[0m json_data [38;5;241m=[39m [43m_get_json_content_from_openml_api[49m[43m([49m
[1;32m    284[0m [43m    [49m[43murl[49m[43m,[49m
[1;32m    285[0m [43m    [49m[43merror_msg[49m[43m,[49m
[1;32m    286[0m [43m    [49m[43mdata_home[49m[38;5;241;43m=[39;49m[43mdata_home[49m[43m,[49m
[1;32m    287[0m [43m    [49m[43mn_retries[49m[38;5;241;43m=[39;49m[43mn_retries[49m[43m,[49m
[1;32m    288[0m [43m    [49m[43mdelay[49m[38;5;241;43m=[39;49m[43mdelay[49m[43m,[49m
[1;32m    289[0m [43m[49m[43m)[49m
[1;32m    290[0m res [38;5;241m=[39m json_data[[38;5;124m"[39m[38;5;124mdata[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mdataset[39m[38;5;124m"[39m]
[1;32m    291[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(res) [38;5;241m>[39m [38;5;241m1[39m:

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/sklearn/datasets/_openml.py:235[0m, in [0;36m_get_json_content_from_openml_api[0;34m(url, error_message, data_home, n_retries, delay)[0m
[1;32m    232[0m         [38;5;28;01mraise[39;00m error
[1;32m    234[0m [38;5;66;03m# 412 error, not in except for nicer traceback[39;00m
[0;32m--> 235[0m [38;5;28;01mraise[39;00m OpenMLError(error_message)

[0;31mOpenMLError[0m: No active dataset miceprotein found.
OpenMLError: No active dataset miceprotein found.

